import {
  faGithub,
  faLinkedinIn,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer/Footer";
import SocialIcon from "../components/SocialIcon/SocialIcon";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Wyatt Schulte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Hi I&apos;m Wyatt Schulte</div>

      <div>currently @ Whop</div>

      <SocialIcon
        icon={faTwitter}
        link={"https://twitter.com/Wyatt_SG"}
        brand={"twitter"}
      />
      <br />
      <SocialIcon
        icon={faLinkedinIn}
        link={"https://www.linkedin.com/in/wyatt-schulte/"}
        brand={"linkedin"}
      />
      <br />
      <SocialIcon
        icon={faGithub}
        link={"https://github.com/Wyatt-SG"}
        brand={"github"}
      />

      <Footer />
    </>
  );
};

export default Home;
